name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [RelWithDebInfo]
        sanitize: [none, asan_ubsan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DVERIFY_WITH_PYTHON=ON \
            -DVV_DSP_BUILD_TESTS=ON \
            ${{ matrix.sanitize == 'asan_ubsan' && '-DVV_DSP_ENABLE_ASAN=ON -DVV_DSP_ENABLE_UBSAN=ON' || '' }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build -j

      - name: Run validation tests
        run: ctest --test-dir build -L validation --output-on-failure

      - name: Run full test suite
        run: ctest --test-dir build --output-on-failure
